name: Deploy Innovatech a AWS

on:
  push:
    branches: [ "deploy" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del codigo
        uses: actions/checkout@v3

      - name: Desplegar en EC2 via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_IP }}
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            mkdir -p /home/ec2-user/proyecto
            cd /home/ec2-user/proyecto
            if [ -d ".git" ]; then
              git pull origin deploy
            else
              git clone -b deploy https://github.com/${{ github.repository }}.git .
            fi
            # Agregamos esta variable para desactivar Buildx
            export DOCKER_BUILDKIT=0
            export COMPOSE_DOCKER_CLI_BUILD=0
            docker-compose up -d --build